#!/usr/bin/env python3
"""Remove test tickets generated by unit tests from the ticket store.

Test tickets are identified by a combination of summary and description
that match well-known placeholder strings used in tests:

  summary (case-insensitive):  "t", "test", "test ticket", "test analysis"
  description (case-insensitive): "test", "test description"

Both fields must match for a ticket to be considered a test ticket;
a real ticket that happens to say "test" in one field is kept.

The script operates via the state store API so the in-memory store
stays consistent. For each matched ticket it will:
  1. Force-close the ticket (if not already closed).
  2. Archive the ticket (removes from active store, moves files to archive).

Usage:
    # Preview what would be removed (default dry-run):
    python3 scripts/clean-test-tickets.py

    # Remove tickets for real:
    python3 scripts/clean-test-tickets.py --apply

    # Target a non-default store:
    python3 scripts/clean-test-tickets.py --store-url http://localhost:8090
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import httpx

# Allow imports from the repo root when the script is run directly.
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

DEFAULT_STORE_URL = "http://localhost:8090"

TEST_SUMMARIES = {"t", "test", "test ticket", "test analysis"}
TEST_DESCRIPTIONS = {"t", "test", "test description"}


def _make_client(store_url: str) -> httpx.Client:
    headers = {}
    token = os.environ.get("AGENTIC_PERF_API_TOKEN", "")
    if not token:
        try:
            from state_store.auth import read_token_from_file

            token = read_token_from_file()
        except Exception:
            pass
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return httpx.Client(base_url=store_url.rstrip("/"), timeout=10.0, headers=headers)


def is_test_ticket(ticket: dict) -> bool:
    summary = ticket.get("summary", "").strip().lower()
    description = ticket.get("description", "").strip().lower()
    return summary in TEST_SUMMARIES and description in TEST_DESCRIPTIONS


def find_test_tickets(client: httpx.Client) -> list[dict]:
    r = client.get("/api/v1/tickets")
    r.raise_for_status()
    return [t for t in r.json() if is_test_ticket(t)]


def force_close(client: httpx.Client, ticket_id: str) -> bool:
    r = client.post(f"/api/v1/tickets/{ticket_id}/force-close")
    if r.status_code == 200:
        return True
    print(
        f"  warning: force-close {ticket_id} failed {r.status_code}: "
        f"{r.json().get('detail', r.text[:60])}",
        file=sys.stderr,
    )
    return False


def archive(client: httpx.Client, ticket_id: str) -> bool:
    r = client.delete(f"/api/v1/tickets/{ticket_id}")
    if r.status_code == 200:
        return True
    print(
        f"  warning: archive {ticket_id} failed {r.status_code}: "
        f"{r.json().get('detail', r.text[:60])}",
        file=sys.stderr,
    )
    return False


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Remove unit-test tickets from the ticket store via the API.",
    )
    parser.add_argument(
        "--store-url",
        default=DEFAULT_STORE_URL,
        help=f"State store URL (default: {DEFAULT_STORE_URL})",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Force-close and archive matched tickets (default is dry-run)",
    )
    args = parser.parse_args(argv)

    client = _make_client(args.store_url)

    try:
        tickets = find_test_tickets(client)
    except httpx.HTTPStatusError as e:
        print(f"Failed to list tickets: {e}", file=sys.stderr)
        return 1
    except httpx.ConnectError:
        print(
            f"Cannot connect to state store at {args.store_url}",
            file=sys.stderr,
        )
        return 1

    # Fetch total count for reporting
    r = client.get("/api/v1/tickets")
    total = len(r.json()) if r.status_code == 200 else "?"

    mode = "APPLYING" if args.apply else "DRY RUN"
    print(f"[{mode}] {total} tickets in store, {len(tickets)} test ticket(s) found\n")

    archived = failed = 0
    for t in tickets:
        tid = t["id"]
        status = t.get("status", "?")
        if args.apply:
            if status != "closed":
                if not force_close(client, tid):
                    print(f"  skipped  {tid} (force-close failed)")
                    failed += 1
                    continue
            if archive(client, tid):
                print(f"  archived {tid}  (was: {status})")
                archived += 1
            else:
                print(f"  failed   {tid}")
                failed += 1
        else:
            print(f"  would archive  {tid}  status={status}  summary={t['summary']!r}")

    print(f"\nTotal in store: {total}")
    print(f"Test tickets:   {len(tickets)}")
    if args.apply:
        print(f"Archived:       {archived}")
        if failed:
            print(f"Failed:         {failed}")
    else:
        print("(dry-run — pass --apply to archive)")

    return 0 if not failed else 1


if __name__ == "__main__":
    raise SystemExit(main())
